# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: atlas-multi-game
#   namespace: web
# spec:
#   replicas: 3
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   selector:
#     matchLabels:
#       app: atlas-multi-game
#   template:
#     metadata:
#       labels:
#         app: atlas-multi-game
#     spec:
#       containers:
#         - name: react
#           image: hrish14/cubbr_d:latest
#           ports:
#             - containerPort: 3000
#           readinessProbe:
#             httpGet:
#               path: /healthz
#               port: 3000
#             initialDelaySeconds: 5
#             periodSeconds: 5
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "100m"
