# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create argocd namespace
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml

# Set default namespace for all resources
namespace: argocd

# Inline namespace definition
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
