---
- name: Setup K3s Kubeconfig on Local Machine
  hosts: localhost
  gather_facts: no
  vars:
    remote_host: "{{ hostvars['my_server']['ansible_host'] }}"
    remote_user: "{{ hostvars['my_server']['ansible_user'] }}"
    remote_kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    local_kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Ensure ~/.kube directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: "0700"

    - name: Copy K3s kubeconfig from remote server
      ansible.builtin.fetch:
        src: "{{ remote_kubeconfig_path }}"
        dest: "{{ local_kubeconfig_path }}"
        flat: yes
      become: yes # Ensures access to the K3s config file
      delegate_to: "{{ remote_host }}"

    - name: Modify kubeconfig to use SSH tunnel (127.0.0.1:6443)
      replace:
        path: "{{ local_kubeconfig_path }}"
        regexp: "server: https://.*"
        replace: "server: https://127.0.0.1:6443"

    - name: Set correct permissions for kubeconfig
      file:
        path: "{{ local_kubeconfig_path }}"
        mode: "0600"

    - name: Start SSH tunnel for Kubernetes API access
      ansible.builtin.command:
        cmd: "ssh -fN -L 6443:127.0.0.1:6443 {{ remote_user }}@{{ remote_host }}"
      async: 0
      poll: 0
