apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/senorbeast/gitops.git
  username: senorbeast
  password: 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
