apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base configurations

# Add production-specific resources
resources:
  - ../../base/argocd
  - ../../base/k3s
  - metallb.yaml
# Optional: Patch existing resources
# patches:
# - patch: argocd-ingress-patch.yaml
